# Default values for 1.0.0.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 0
  
remoteWrite: "http://172.16.254.1:9090"

clusterName: demo
clusterEnv: dev
